openapi: 3.0.4
info:
  title: Antonym Finder
  description: Antonym is a simple tool for getting the antonyms of a word. It returns a list of antonyms for the given word.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/antonym:
    get:
      summary: Get Antonyms of Word
      description: Antonym is a simple tool for getting the antonyms of a word. It returns a list of antonyms for the given word.
      operationId: antonym
      parameters:
      - name: word
        in: query
        schema:
          type: string
        required: true
        description: The word to get the antonyms for
        example: happy
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  word: happy
                  antonyms:
                  - sad
                  - unhappy
                  - miserable
                  - depressed
                  - gloomy
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
